name: Deploys to dockerhub

on:
  workflow_run:
    workflows:
      - "Validate python versions"
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        name: Checkout latest commit


      - name: Prijava v Docker
        run: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD


      - name: Zapakiraj in pushni
        run: |
            sh $GITHUB_WORKSPACE/zapakiraj_27118.sh

      
