name: Validate python versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:



jobs:
  checkForTests:
    runs-on: self-hosted
    steps:
      # prenese zadnji commit
      - uses: actions/checkout@v2
        name: Check out current commit

      # zazene bash skripto ki preveri ce specifična .py datoteka obstaja v tem primeru test_math.py
      - name: Check if files exist
        run: |
          if [ -f $GITHUB_WORKSPACE/test_math.py ]; then
            echo "File exists"
            echo 1 > file.txt
          else
            echo "File does not exist"
            echo 0 > file.txt
          fi
      - name: Nalozi artifakt
        uses: actions/upload-artifact@v4
        with:
          name: file_exists
          path: file.txt
          retention-days: 1

  build:
    needs: checkForTests # prejsni job se mora uspešno zagnati
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.9.0, 3.10.0, 3.11.0, 3.12.0] # zažene naslednje stepe z vsemi verzijami tukaj
    steps:
      - name: Prenesi artifakt
        uses: actions/download-artifact@v4
        with:
          name: file_exists

      - name: Preveri ce je bil artifakt vredu
        run: |
          value=`cat file.txt`
          rm file.txt
          if [ $value=0 ]; then
            exit 1
          fi

      - uses: actions/checkout@v4
      - name: Nastavi Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # zazene python da nalozi vse pip dependencie
      - name: Namesti odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # zažene pytest
      - name: Do tests
        run: pytest
