name: Deploys to dockerhub

on:
  workflow_run:
    workflows:
      - "Validate python versions"
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # si prenese zadnji commit iz repositorija
      - uses: actions/checkout@v4
        name: Checkout latest commit


#      - name: Prijava v Docker
#        run: |
#          echo ${{ secrets.DOCKERHUB_TOKEN }} > pass.txt
#          cat pass.txt | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#          rm pass.txt

      # NAVADN LOGIN NI DELO zato sm uporabo cation da se logina :)
      # probo sm 5 različnih načinov do tega da so mi bennal ip iz dockera
      - name: Prijava v Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # zažene skripto zapakiraj_27118.sh
      - name: Zapakiraj in pushni
        run: |
            sh zapakiraj_27118.sh

      
