name: Deploys to dockerhub

on:
  workflow_run:
    workflows:
      - "Validate python versions"
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        name: Checkout latest commit


      - name: Prijava v Docker
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} > pass.txt
          echo ${{ secrets.DOCKERHUB_USERNAME }} > test.txt
          cat test.txt
          cat pass.txt | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          rm pass.txt


      - name: Zapakiraj in pushni
        run: |
            sh $GITHUB_WORKSPACE/zapakiraj_27118.sh

      
