name: Deploys to dockerhub

on:
  workflow_run:
    workflows:
      - "Validate python versions"
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        name: Checkout latest commit


      - name: Prijava v Docker
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD


      - name: Zapakiraj in pushni
        run: |
            sh $GITHUB_WORKSPACE/zapakiraj_27118.sh

      
