name: Validate python versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:



jobs:
  checkForTests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit

      - name: Check if files exist
        run: |
          if [ -f test_math.py ]; then
            echo "File exists"
            exit 1
          else
              echo "File does not exist"
          fi

  build:
    needs: checkForTests
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.9.0, 3.10.0, 3.11.0, 3.12.0]
    steps:
      - uses: actions/checkout@v4

      - name: Nastavi Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Namesti odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Do tests
        run: pytest
