name: Validate python versions

on:
  push:
    branches:
      - main


jobs:
  checkForTests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit

      - name: Check if files exist
        if: ${{ hashFiles('.tests/') != ''}}
        run: |
          echo "Test files exist"

  build:
    needs: checkForTests
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.9, 3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v2

      - name: Nastavi Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Namesti odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Do tests
        run: pytest
