name: Deploys to dockerhub

on:
  push:
    branches: [ main,test ]
  pull_request:
    branches: [ main ]



jobs:
  temporary:
    runs-on: self-hosted
    steps:
      - name: Just for fun
        run: |
          echo "Test files exist"
